### ISSUE TITLE
layout里面的根布局能改吗？

### ISSUE THREAD

**Issue by lolkt** [asjqkkkk/TemplatesTest#1]
线性布局

**Comment by asjqkkkk** [comment]
可以的，想改成什么布局，自己设置就行啦！

**Comment by lolkt** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".mvp.BizActivity">

</android.support.constraint.ConstraintLayout>`


怎么改成 LinearLayout，请教在哪设置？

**Comment by asjqkkkk** [comment]
很明显了哦，你在xml里面写一个基础的LinearLayout布局，将上面的内容替换调就行啦！
不过目前推荐使用ConstraintLayout作为默认布局哦，因为它是最好用的
